import { css, useTheme } from '@emotion/react';
import { ReactElement } from 'react';
import PageLayout from '../../PageLayout';
import defaultTheme from '../../theme';

const DiseaseModel = (): ReactElement => {
	const theme: typeof defaultTheme = useTheme();

	return (
		<PageLayout subtitle="Disease Model">
			{/* Page header */}
			<section
				css={css`
					background: linear-gradient(135deg, ${theme.colors.primary_darker} 10%, ${theme.colors.primary} 50%, ${theme.colors.primary_lightest} 100%);
					color: ${theme.colors.white};
					padding: 56px 24px;
					text-align: center;
				`}
			>
				<h1
					css={css`
						font-family: 'Geomanist', sans-serif;
						font-size: 2rem;
						font-weight: 700;
						margin: 0 0 16px;
					`}
				>
					Disease Model
				</h1>
				<p
					css={css`
						font-family: 'Geomanist', sans-serif;
						font-size: 1.05rem;
						font-weight: 300;
						opacity: 0.88;
						max-width: 640px;
						margin: 0 auto;
						line-height: 1.6;
					`}
				>
					Visualisations and results from the SEED-ALS computational analysis team, including
					machine learning models applied to ALS research data.
				</p>
			</section>

			{/* Coming soon */}
			<section
				css={css`
					flex: 1;
					background-color: ${theme.colors.primary_palest};
					border-bottom: 1px solid ${theme.colors.primary_pale};
					display: flex;
					align-items: center;
					justify-content: center;
					padding: 80px 24px;
				`}
			>
				<div
					css={css`
						max-width: 560px;
						width: 100%;
						text-align: center;
						display: flex;
						flex-direction: column;
						align-items: center;
						gap: 24px;
					`}
				>
					{/* Icon */}
					<div
						css={css`
							width: 72px;
							height: 72px;
							border-radius: 50%;
							background-color: ${theme.colors.primary_pale};
							border: 2px solid ${theme.colors.primary_light};
							display: flex;
							align-items: center;
							justify-content: center;
							font-size: 1.8rem;
						`}
					>
						⧗
					</div>

					<div
						css={css`
							display: flex;
							flex-direction: column;
							gap: 12px;
						`}
					>
						<h2
							css={css`
								font-family: 'Geomanist', sans-serif;
								font-size: 1.4rem;
								font-weight: 700;
								color: ${theme.colors.primary};
								margin: 0;
							`}
						>
							Under development
						</h2>
						<p
							css={css`
								font-family: 'Geomanist', sans-serif;
								font-size: 0.95rem;
								color: ${theme.colors.grey_5};
								line-height: 1.8;
								margin: 0;
							`}
						>
							This section will present the results generated by the machine learning
							team. The specific visualisations and analyses will be defined as the computational
							workflows are finalised.
						</p>
					</div>

					<span
						css={css`
							display: inline-block;
							font-family: 'Geomanist', sans-serif;
							font-size: 0.8rem;
							font-weight: 700;
							color: ${theme.colors.primary};
							background-color: ${theme.colors.primary_pale};
							border: 1px solid ${theme.colors.primary_light};
							border-radius: 20px;
							padding: 6px 18px;
							letter-spacing: 0.06em;
							text-transform: uppercase;
						`}
					>
						Coming soon
					</span>
				</div>
			</section>
		</PageLayout>
	);
};

export default DiseaseModel;
